"map_settings"
{

	"bm2_legacy"
	{
	    "maxLanes"          "1"
	    "maxTier"           "4"
	    "maxPlayers"        "4"
	    "maxTree1"			"2"
	    "maxTree2"			"0"
	}

	"bm2_mexican_standoff"
	{
	    "maxLanes"          "1"
	    "maxTier"           "2"
	    "maxPlayers"        "2"
	    "maxTree1"			"1"
	    "maxTree2"			"2"
	}


	"bm2_cold_war"
	{
	    "maxLanes"          "2"
	    "maxTier"           "4"
	    "maxPlayers"        "8"
	}
}